spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/store-service
    username: 
    password:
    driverClassName: org.postgresql.Driver

server:
  port: 6080